openapi: "3.0.0"
info:
  title: Callbacks Object
  version: "1.0.0"  
  
paths: 

  /pets:
    get:
      summary: Read
      description: Provide details for the entire list (for collection resources) or an item (for object resources)
      responses:
        201:
          description: Null response
      callbacks:
        #KZOE-template name="callbacks in operation", value="callbacks"
        
        myWebhook:
          #KZOE-template name="callback in operation", value="callback"
          $ref: "#/components/callbacks/myWebhook"

components: 

  callbacks:
    #KZOE-template name="callbacks in components/callbacks", value="callbacks"
    
    MyWebhooWithRef:
      #KZOE-template name="callback in components/callback", value="callback"
      $ref: "#/components/callbacks/myWebhook"
    myWebhook:
      '$request.body#/url':
        post:
          requestBody:
            description: Callback payload
            content: 
              'application/json':
                schema:
                  $ref: '#/components/schemas/SomePayload'
          responses:
            '200':
              description: webhook successfully processed and no retries will be performed

    statusCallback:
      #KZOE-template name="1 callbacks in components/callback", value="callback"
      /statusUpdate:
        #KZOE-template name="2 operation template", value="pathItem"
        post:
          operationId: StatusUpdateCallback
          description: |
            POST method to be implemented by the client. BeamUp will 
            call this method to advise on the status of a requested, in-progress,
            or completed trip.
          requestBody:
            description: content of the status update notification.
            content: 
              #KZOE-template name="3 mediatypes template", value="mediaTypes"
              "application/json":
                schema:
                  #KZOE-template name="4 schema template", value="schema"
                  type: object
                  properties:
                    tripId: 
                      type: string
                    tripStatusCode:
                      type: string
                      enum:
                      - REQUESTED
                      - IN_PROGRESS
                      - COMPLETED
                      - CANCELLED
                    eta:
                      type: string
                      format: date-time
          responses:
            #KZOE-template name="7 response", value="responses"
            200: 
              description: Normal response to acknowledge a status update.
