openapi: "3.0.0"
info:
  title: Callbacks Object
  version: "1.0.0"  
  
paths: 

  /pets:
    get:
      summary: Read
      description: Provide details for the entire list (for collection resources) or an item (for object resources)
      responses: {}
      callbacks:
        #KZOE-template name="callbacks in operation", value="callbacks"
        myWebhook:
          #KZOE-template name="callback in operation", value="callback"
          $ref: "#/components/callbacks/myWebhook"

components: 

  callbacks:
    #KZOE-template name="callbacks in components/callbacks", value="callbacks"
    MyWebhooWithRef:
      #KZOE-template name="callback in components/callback", value="callback"
      $ref: "#/components/callbacks/myWebhook"
    myWebhook:
      '$request.body#/url':
        post:
          requestBody:
            description: Callback payload
            content: 
              'application/json':
                schema:
                  $ref: '#/components/schemas/SomePayload'
          responses:
            '200':
              description: webhook successfully processed and no retries will be performed

 