openapi: "3.0.0"
info:
  title: Security Schemes Object
  version: "1.0.0"  
  
paths: 

  /pets:
    get:
      summary: Read
      description: Provide details for the entire list (for collection resources) or an item (for object resources)
      responses: {}
      security:
        - petstore_auth:
          - write:pets
          - read:pets

components: 

  securitySchemes:
    #KZOE-template name="securitySchemes in components/securitySchemes", value="securitySchemes"
    api_key:
      #KZOE-template name="security scheme object in components", value="securityScheme"
      type: apiKey 
      name: api_key
      in: header
    petstore_auth:
      type: oauth2
      flows: 
        implicit:
          authorizationUrl: http://example.org/api/oauth/dialog
          scopes:
            write:pets: modify pets in your account
            read:pets: read your pets

 