openapi: "3.0.0"
info:
  title: Callbacks Object
  version: "1.0.0"  
  
paths: 

  /pets:
    get:
      summary: Read
      description: Provide details for the entire list (for collection resources) or an item (for object resources)
      responses: {}
      callbacks:
        myWebhook:
         # Operation: KaiZen code assist OK
          $ref: "#/components/callbacks/myWebho ok"

components: 

  callbacks:
    myWebhook:
      '$request.body#/url':
        post:
          requestBody:
            description: Callback payload
            content: 
              'application/json':
                schema:
                  $ref: '#/components/schemas/SomePayload'
          responses:
            '200':
              description: webhook successfully processed and no retries will be performed

 