openapi: "3.0.0"
info:
  title: Callbacks Object
  version: "1.0.0"  
  
paths: 

  /pets:
    $ref: "HeadersObject.yaml#/paths/~1pets"
      
components: 

  callbacks:
    myWebhook:
      '$request.body#/url':
        $ref: "HeadersObject.yaml#/paths/~1pets"

 