openapi: "3.0.0"
info:
  title: Callbacks Object
  version: "1.0.0"  
  
paths: 

  /pets:
    #KZOE-ref name="path item in paths", value="paths"
    $ref: "HeadersObject.yaml#/paths/~1pets"
      
components: 

  callbacks:
    myWebhook:
      '$request.body#/url':
        #KZOE-ref name="path item in callback", value="paths"
        $ref: "HeadersObject.yaml#/paths/~1pets"

 