openapi: "3.0.0"
info:
  title: Schema Object
  version: "1.0.0"
  
paths:
  /resource:
    get:
      description: description
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  #KZOE-ref name="schema in content array", value="components/schemas"
                  $ref: '#/components/schemas/StringToModelMappingObject'
            '*/*' :
               schema: 
                 #KZOE-ref name="schema in content", value="components/schemas"
                 $ref: "#/components/schemas/SimpleObject"
          
components:
  schemas:
  
    SimpleObject:
      type: object
      required:
      - name
      properties:
        name:
          type: string
        address:
          #KZOE-ref name="schema in properties", value="components/schemas"
          $ref: "#/components/schemas/Pet"
        age:
          type: integer
          format: int32
          minimum: 0    
        
    StringToModelMappingObject:
      type: object
      additionalProperties:
        #KZOE-ref name="schema in additionalProperties", value="components/schemas"
        $ref: "#/components/schemas/Dog"
        
    ExtendedErrorModel:
      allOf:
        #KZOE-ref name="schema in allOf", value="components/schemas" kzoe-arrayItem
      - $ref: '#/components/schemas/ErrorModel'
      - type: object
        required:
        - rootCause
        properties:
          rootCause:
            type: string
            
    WithAnyOf:  ## 
      description: A representation of a cat
      anyOf:
        #KZOE-ref name="schema in anyOf", value="components/schemas" kzoe-arrayItem
      - $ref: '#/components/schemas/Pet'
      - type: object
        properties:
          huntingSkill:
            type: string
            description: The measured skill for hunting
            enum:
            - clueless
            - lazy
            - adventurous
            - aggressive
        required:
        - huntingSkill
 
    AnyOfWithNestedSchema:  ## 
      description: A representation of a cat
      anyOf:
      - type: object
        properties:
          huntingSkill:
            #KZOE-ref name="schema in anyOf", value="components/schemas" kzoe-arrayItem
            $ref: "#/components/schemas/SimpleObject"
                
    # Discrinimator Object
    MyResponseType:
      oneOf:
        #KZOE-ref name="schema in oneOf", value="components/schemas" kzoe-arrayItem
        - $ref: '#/components/schemas/Cat'
        - $ref: '#/components/schemas/Dog'
        - $ref: '#/components/schemas/Lizard'
      discriminator:
          propertyName: pet_type       
          
          
    SchemaItems:
      type: array
      items:
        #KZOE-ref name="schema in items", value="components/schemas" kzoe-arrayItem
        $ref: ""

  parameters:
    username:
      name: username
      in: path
      description: username to fetch
      required: true
      schema:
        #KZOE-ref name="schema in parameter", value="components/schemas"
        $ref: "#/components/schemas/SimpleObject"
           
  headers:
    X-Rate-Limit-Reset:
      description: The number of seconds left in the current period
      schema:
        #KZOE-ref name="schema in header", value="components/schemas"
        $ref: "#/components/schemas/SimpleObject"    
                     
  